version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testbox2
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=postgres://bnjkzntbapnmdn:18534be735d3c2ffe16221ef1a661b41e1bd99a498d171b80d4a9e4a7b1b09ce@ec2-54-75-249-16.eu-west-1.compute.amazonaws.com:5432/db0jbnc73pi70s
      - DATABASE_SCHEMA=public
      - DATABASE_SSL=false
      - FOREST_AUTH_SECRET=21c68718de6f2a853301affaf18360178b4c826a30178d11
      - FOREST_ENV_SECRET=41163c2720eac78d5657750686eb28c5ae84c9e700721a94efecb46fb962d944
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
